### PR TITLE
Add Django 1.11 compatibility

### PR DESCRIPTION
**Pull request by rfadams**
For details, see #259

### CODE REVIEW

**Comment by jfunction** [comment]
Thanks @rfadams for this. This library is a dependency for django-edge which is otherwise compatible with 1.11.9 so I'm interested in these commits - will push them as a submodule. 

Was there a reason you chose to override `render_to_string` rather than ensuring `context` was a dict as recommended in [the docs](https://docs.djangoproject.com/en/1.11/releases/1.11/#django-template-backends-django-template-render-prohibits-non-dict-context)?

**Comment by darreola** [comment]
is this repository dead?

**Comment by xrmx** [comment]
@darreola there's already an responsive mobile friendly interface in django 2.0 which is installable as separated packages for older django version. I don't see much point in moving this forward.

**Comment by markddavidoff** [comment]
2.0 requires python 3 which can be a tricky switch for some. Since 2.7 is not EOL until 2020, I expect there will still be use of this until at least then.

**Comment by rfadams** [comment]
Stale. Closing.

**Pull request closed without merging**
