### PR TITLE
render custom header if exists

### PR DESCRIPTION
**Pull request by aliva**
I wanted to add a few contents in header section without copying your templates into my app and editing them, so I think it's a good idea to try loading my custom templates while rendering page.

### CODE REVIEW

**Comment by xrmx** [comment]
Thanks for the patch. Unfortunately am not going to apply it, it's not sustainable to add custom hooks for every situation. I know copying a template just for a line is lame but it's how django template inheritance currently work.

**Comment by aliva** [comment]
hmm, ok.

so my actual need for custom template is adding rtl support for admin page, so what do you think about adding rtl (right-to-left) support to your repo (It may need some extra css files to be added for rtl pages)

**Comment by xrmx** [comment]
Nice! Patches to add proper RTL support are more than welcome :) Are you going to use https://github.com/morteza/bootstrap-rtl right?

**Comment by aliva** [comment]
yeah I tried it and it works perfect :)

**Pull request closed without merging**
