### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by d33tah**
I noticed that you have a test directory and tests are mentioned are mentioned in setup.db. Perhaps you could benefit from automated integration tests? Once you set up a free Travis CI account linked to your GitHub, those would happen automatically once you push anything not labeled with [ci skip] and
if any tests fail, you'll get an e-mail. Also, you'll be getting your pull requests tested the same way and you can test for multiple Django/Python versions easily.

### CODE REVIEW

**Comment by xrmx** [comment]
Thanks, cool stuff! any chance you can squash all the commits in two, one creating the file and the other one adding the swag to README please?

**Comment by d33tah** [comment]
I performed a force-push that solved it. Surprisingly, Github reacted to that well!

**Comment by xrmx** [comment]
that's how it is supposed to behave: force push is the standard for redoing pull request :) thanks!

**Comment by d33tah** [comment]
@xrmx: Ah, since you merged it into master, correct `README.rst`, removing `?branch=travis-ci` from the image URL.

**Comment by d33tah** [comment]
@xrmx: Also, it looks like you didn't enable Travis CI yet. Register on https://travis-ci.org/ with your Github account, log in and enable your repository there.

**Comment by d33tah** [comment]
@xrmx: This screenshot is pretty informative: http://practicalmeteor.com/wp-content/uploads/2014/12/Travis-CI-Enable-repo.png - once you've done that, send a test commit and see if CI kicked in. Build logs should be easily visible for everybody then.

**Comment by xrmx** [comment]
I already got an email when i merged your pull request. Isn't this working for you?
https://travis-ci.org/django-admin-bootstrapped/django-admin-bootstrapped

**Comment by d33tah** [comment]
Ah, sorry, you're right, I just expected a note below the commit string, perhaps I remembered something wrong. Anyway, I confirm that it works.

BTW, it looks like the image points to my username in the README, this probably needs fixing as well.

**Comment by xrmx** [comment]
@d33tah fixed, thanks

**Pull request merged**
